"""table

Revision ID: 3a6568d8bfa4
Revises: 
Create Date: 2018-04-12 12:15:49.847443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6568d8bfa4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('userval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freq', sa.Integer(), nullable=True),
    sa.Column('amp', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userval_amp'), 'userval', ['amp'], unique=True)
    op.create_index(op.f('ix_userval_freq'), 'userval', ['freq'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userval_freq'), table_name='userval')
    op.drop_index(op.f('ix_userval_amp'), table_name='userval')
    op.drop_table('userval')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
